import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={` antialiased bg-slate-900 max-w-[1600px] mx-auto`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
